# Model Building

Import data and libraries into R

```{r}
census = read.csv('/Users/lindegaard/Documents/GitHub Repo/exercise01_consolidated.csv')
library(ggplot2)
library(dplyr)
library(InformationValue)


```

Clean data and exploratory analysis



```{r}
#Perform a simple exploratory analysis and generate summary statistics to get a sense of what is in the data.

#Exploring the types of data
for (x in 1:23) {
  print(colnames(census[x]))
  print(class(census[,x]))
}
# Explore values in larger categorical variables
table(census$education_level)
# If there are less than 20 levels, factorize the variable
for (x in 1:23) {
  if (length(table(census[,x])) < 20)
  census[,x] = as.factor(census[,x])
}

# Country is currently not a factor - manually factorize
census$country = as.factor(census$country)
census$country_id = as.factor(census$country_id)

# Check the variables that are not treated as factors
for (x in 1:23) {
  if (class(census[,x]) != "factor") {
    print(colnames(census[x]))
    print(class(census[,x]))
  }
}


## Check for NA Values (represented with "?") in each variable
sapply(census, function(x) any(x == "?"))
# NA Values in workclass, occupation and country, but they will be treated as an individual category in each of these factor variables



```


Split data into training, validation and test

```{r}
#Split the data into a 70/20/10 training, validation, and test data split.
```

Clean data and Develop Model

```{r}
#Develop a model that predicts whether individuals, based on the census variables provided, make over $50,000/year. Use over_50k as the target variable.
#Commit enough code to reproduce your full model selection process, including your final model and all models developed along the way.
```

Create a chart

```{r}
#Create a chart that you feel conveys one important relationship in the data.

```
